basic wishlist CRUD operations and docs to swagger
ets-ninja/honeyMoney_backend pull request #16
Opened 2022-09-29 11:08 UTC by ChebotarYuliia

2022-09-29 14:55 UTC, npelenskii approved these changes

2022-09-30 06:58 UTC, ShevtsovVolodymyr commented on docs/swagger.json
> +        "tags": ["Wishlist"],
```suggestion
        "tags": ["Wishlist"],
        "security": {
          "bearerAuth": []
        },
```

2022-09-30 07:00 UTC, ShevtsovVolodymyr commented on docs/swagger.json
> +        "summary": "Create a new item in the user's wishlist",
```suggestion
        "summary": "Create a new item in the user's wishlist",
        "security": {
          "bearerAuth": []
        },
```

2022-09-30 08:12 UTC, ShevtsovVolodymyr requested changes, later dismissed
Please add security prop to documentation (Authorization required) for jwt protected routes

2022-10-03 08:39 UTC, ShevtsovVolodymyr approved these changes

2022-10-03 11:28 UTC, merged